import os
from typing import Optional, List

import streamlit as st
from dotenv import load_dotenv

from google import genai

from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.language_models.llms import LLM
from langchain_core.embeddings import Embeddings

from sentence_transformers import SentenceTransformer


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI Diagnosis Assistant",
    page_icon="👨‍⚕️",
    layout="centered"
)


# ============================================================
# EMBEDDINGS
# ============================================================

class HuggingFaceEmbeddings(Embeddings):

    def __init__(self, model_name="all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)

    def embed_documents(self, texts):
        return [
            self.model.encode(text).tolist()
            for text in texts
        ]

    def embed_query(self, text):
        return self.model.encode(text).tolist()


# ============================================================
# GEMINI LLM
# ============================================================

class GeminiLLM(LLM):

    model: str = "gemini-3.5-flash"

    api_key: Optional[str] = os.getenv(
        "GEMINI_API_KEY"
    )

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None
    ) -> str:

        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY not found in .env"
            )

        client = genai.Client(
            api_key=self.api_key
        )

        response = client.models.generate_content(
            model=self.model,
            contents=prompt
        )

        if response.text:
            return response.text

        return "No response was generated by Gemini."

    @property
    def _identifying_params(self) -> dict:
        return {
            "model": self.model
        }

    @property
    def _llm_type(self) -> str:
        return "gemini"


# ============================================================
# TITLE
# ============================================================

st.title("👨‍⚕️ AI Diagnosis Assistant")

st.warning(
    "This Source is for educational use and should not replace medical advice."
    "Please consult a qualified healthcare provider."
    "This I did for my undersatdings only"
)


# ============================================================
# EXIT SESSION
# ============================================================

if "exit_app" not in st.session_state:
    st.session_state.exit_app = False


if st.session_state.exit_app:

    st.title("🩺 AI Diagnosis Assistant")

    st.info(
        "The session has been ended. "
        "You can close this browser tab."
    )

    if st.button(
        "Start Again",
        use_container_width=True
    ):

        st.session_state.exit_app = False
        st.rerun()

    st.stop()


# ============================================================
# LOAD EMBEDDING MODEL
# ============================================================

@st.cache_resource
def load_embeddings():

    return HuggingFaceEmbeddings(
        model_name="all-MiniLM-L6-v2"
    )


embeddings = load_embeddings()


# ============================================================
# LOAD FAISS VECTOR DATABASE
# ============================================================

@st.cache_resource
def load_vectorstore():

    return FAISS.load_local(
        "medical_vectordb",
        embeddings,
        allow_dangerous_deserialization=True
    )


try:

    vectorstore = load_vectorstore()

except Exception as e:

    st.error(
        f"Error loading knowledge base: {e}"
    )

    st.info(
        "Make sure the 'medical_vectordb' folder exists. "
        "Run create_knowledge_base.py first."
    )

    st.stop()


# ============================================================
# RETRIEVER
# ============================================================

retriever = vectorstore.as_retriever(
    search_kwargs={
        "k": 4
    }
)


# ============================================================
# GEMINI CONFIGURATION
# ============================================================

try:

    if not os.getenv("GEMINI_API_KEY"):

        raise ValueError(
            "GEMINI_API_KEY not found in .env"
        )

    llm = GeminiLLM()

except Exception as e:

    st.error(
        f"Gemini configuration error: {e}"
    )

    st.stop()


# ============================================================
# PROMPT TEMPLATE
# ============================================================

prompt_tmpl = PromptTemplate(
    template=(
        "You are a careful medical assistant.\n\n"

        "Use the provided medical knowledge context "
        "to answer the user's question.\n\n"

        "The patient's information is provided in this format:\n"
        "- Symptoms\n"
        "- Duration\n"
        "- Severity\n\n"

        "Important instructions:\n"
        "1. Do not claim to provide a definitive diagnosis.\n"
        "2. Provide possible explanations or differential diagnoses.\n"
        "3. Consider the symptom duration and severity.\n"
        "4. Mention important warning signs or red flags.\n"
        "5. Provide general next steps.\n"
        "6. If the available medical context does not contain "
        "enough information, clearly say so.\n"
        "7. Do not invent information that is not supported "
        "by the medical context.\n"
        "8. Always include: "
        "'Disclaimer: Consult a doctor.'\n\n"

        "Medical Knowledge Context:\n"
        "{context}\n\n"

        "Patient Information:\n"
        "{question}\n\n"

        "Answer:"
    ),
    input_variables=[
        "context",
        "question"
    ]
)


# ============================================================
# FORMAT DOCUMENTS
# ============================================================

def format_docs(docs):

    return "\n\n".join(
        doc.page_content
        for doc in docs
    )


# ============================================================
# RAG FUNCTION
# ============================================================

def rag_answer(question: str):

    # --------------------------------------------------------
    # 1. Retrieve relevant medical information
    # --------------------------------------------------------

    docs = retriever.invoke(
        question
    )

    # --------------------------------------------------------
    # 2. Convert documents into context
    # --------------------------------------------------------

    context = format_docs(
        docs
    )

    # --------------------------------------------------------
    # 3. Create prompt
    # --------------------------------------------------------

    prompt = prompt_tmpl.format(
        context=context,
        question=question
    )

    # --------------------------------------------------------
    # 4. Generate answer using Gemini
    # --------------------------------------------------------

    answer = llm.invoke(
        prompt
    )

    return str(answer), docs


# ============================================================
# PATIENT INFORMATION
# ============================================================

st.subheader("Patient Information")


# ============================================================
# SYMPTOMS
# ============================================================

symptoms = st.text_area(
    "What symptoms are you experiencing?",
    placeholder=(
        "Example: Fever, headache, cough and sore throat"
    ),
    height=100
)


# ============================================================
# DURATION
# ============================================================

duration = st.text_input(
    "How long have you been experiencing these symptoms?",
    placeholder=(
        "Example: 2 days, 5 hours, 1 week"
    )
)


# ============================================================
# SEVERITY
# ============================================================

severity = st.selectbox(
    "How severe are your symptoms?",
    [
        "Select severity",
        "Low",
        "Medium",
        "High"
    ]
)


# ============================================================
# MEDICAL REPORT PDF
# CURRENTLY DISABLED
# ============================================================

# If you want to enable medical report upload later,
# uncomment this section.


# import pymupdf as fitz


# uploaded_pdf = st.file_uploader(
#     "Upload medical report (PDF):",
#     type="pdf"
# )


# ============================================================
# MEDICAL REPORT PROCESSING
# CURRENTLY DISABLED
# ============================================================


# pdf_text = ""


# if uploaded_pdf:
#
#     try:
#
#         with open("temp.pdf", "wb") as f:
#             f.write(
#                 uploaded_pdf.getbuffer()
#             )
#
#         with fitz.open("temp.pdf") as pdf:
#
#             for page in pdf:
#
#                 try:
#
#                     text = page.get_text("text")
#
#                     if text:
#
#                         pdf_text += text + " "
#
#                     else:
#
#                         st.warning(
#                             f"Skipping page "
#                             f"{page.number + 1}: "
#                             f"no text extracted"
#                         )
#
#                 except Exception as e:
#
#                     st.warning(
#                         f"Error reading page "
#                         f"{page.number + 1}: {e}"
#                     )
#
#         os.remove("temp.pdf")
#
#     except Exception as e:
#
#         st.error(
#             f"Error processing uploaded PDF: {e}"
#         )


# ============================================================
# BUTTONS
# ============================================================

col1, col2 = st.columns(2)


with col1:

    get_diagnosis = st.button(
        "🔍 Get Diagnosis",
        type="primary",
        use_container_width=True
    )


with col2:

    exit_button = st.button(
        "❌ Exit",
        use_container_width=True
    )


# ============================================================
# EXIT BUTTON
# ============================================================

if exit_button:

    st.session_state.exit_app = True

    st.rerun()


# ============================================================
# GET DIAGNOSIS
# ============================================================

if get_diagnosis:

    # --------------------------------------------------------
    # CHECK SYMPTOMS
    # --------------------------------------------------------

    if not symptoms.strip():

        st.warning(
            "Please describe your symptoms."
        )

    # --------------------------------------------------------
    # CHECK DURATION
    # --------------------------------------------------------

    elif not duration.strip():

        st.warning(
            "Please specify how long you have "
            "been experiencing these symptoms."
        )

    # --------------------------------------------------------
    # CHECK SEVERITY
    # --------------------------------------------------------

    elif severity == "Select severity":

        st.warning(
            "Please select the severity of your symptoms: "
            "Low, Medium, or High."
        )

    # --------------------------------------------------------
    # ALL INFORMATION AVAILABLE
    # --------------------------------------------------------

    else:

        # ----------------------------------------------------
        # Create structured patient information
        # ----------------------------------------------------

        patient_information = f"""
Symptoms: {symptoms}

Duration: {duration}

Severity: {severity}
"""

        # ----------------------------------------------------
        # Display collected information
        # ----------------------------------------------------

        with st.expander(
            "Patient Information",
            expanded=False
        ):

            st.write(
                f"**Symptoms:** {symptoms}"
            )

            st.write(
                f"**Duration:** {duration}"
            )

            st.write(
                f"**Severity:** {severity}"
            )

        # ----------------------------------------------------
        # RAG + GEMINI
        # ----------------------------------------------------

        with st.spinner(
            "Searching medical knowledge and generating response..."
        ):

            try:

                # ------------------------------------------------
                # Retrieve and generate
                # ------------------------------------------------

                answer, source_docs = rag_answer(
                    patient_information
                )

                # ------------------------------------------------
                # Display response
                # ------------------------------------------------

                st.markdown(
                    "### Response"
                )

                st.write(
                    answer
                )

                # ------------------------------------------------
                # Display source pages
                # ------------------------------------------------

                pages = [
                    doc.metadata.get(
                        "page",
                        "Unknown"
                    )
                    for doc in source_docs
                ]

                if pages:

                    unique_pages = list(
                        dict.fromkeys(pages)
                    )

                    st.markdown(
                        "**Source Pages:** "
                        + ", ".join(
                            map(
                                str,
                                unique_pages
                            )
                        )
                    )

            except Exception as e:

                st.error(
                    f"Error generating response: {e}"
                )